

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    labels:
      - "maintainer=rexi1r rexi1r@yahoo.com"
      - "version=1.0"
      - "description=JAM MONGODB"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks: [app]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    labels:
      - "maintainer=rexi1r rexi1r@yahoo.com"
      - "version=1.0"
      - "description=JAM BACKEND"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/contracts?authSource=admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:80,http://localhost:3000}
    depends_on:
      - mongo
    networks: [app]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo
    networks: [app]

  # سرویس فرانت تنها در محیط توسعه build و اجرا می‌شود
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    labels:
      - "maintainer=rexi1r rexi1r@yahoo.com"
      - "version=1.0"
      - "description=JAM FRONT END"
    environment:
      - NGINX_ENV=${NGINX_ENV:-development}
      - DOMAIN=${DOMAIN:-localhost}
    depends_on:
      - backend
    networks: [app]

  nginx:
    # استفاده از Dockerfile سفارشی nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    labels:
      - "maintainer=rexi1r rexi1r@yahoo.com"
      - "version=1.0"
      - "description=JAM NGINX"
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_ENV=${NGINX_ENV:-development}
      - DOMAIN=${DOMAIN:-localhost}
    volumes:
      # گواهی‌ها (اختیاری – در صورت استفاده از certbot)
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      # خروجی build فرانت‌اند (برای prod)
      - ./frontend/build:/usr/share/nginx/html:ro
    networks: [app]

  # سرویس تجدید گواهی‌ها (اختیاری)
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done"

networks:
  app: {}

volumes:
  mongo_data: {}
  certbot-etc: {}
  certbot-var: {}
