services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npx","nodemon","server.js"]
    environment:
      NODE_ENV: development

  frontend:
    build: null
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # نصب وابستگی‌ها در هر بار راه‌اندازی و سپس اجرای سرور توسعه
    command: ["sh","-c","npm ci && npm run dev -- --host --port 80"]
    environment:
      NODE_ENV: development
